name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

  pull_request:
    branches:
      - master

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[SKIP]') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install gtest
        run: |
          mkdir build && cd build
          git clone -b release-1.11.0 --depth=1 https://github.com/google/googletest.git googletest
          cd googletest && mkdir gtest_build && cd gtest_build
          sudo cmake .. && sudo make
          sudo make install
      - name: Compile
        if: ${{ success() }}
        shell: bash
        run: |
          gcc --version
          cd build
          cmake -DASAN=ON -DCOVERAGE=ON -DSTRICT_ERROR=ON ..
          make
      - name: Run Testcase
        run: ./build/bin/Cbox-test
      - name: Repo covered
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
