name: Build

on: push

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[SKIP]') == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install gtest
        run: |
          mkdir build && cd build
          git clone -b release-1.11.0 --depth=1 https://github.com/google/googletest.git googletest
          cd googletest && mkdir gtest_build && cd gtest_build
          sudo cmake .. && sudo make
          sudo make install
      - name: Compile
        if: ${{ success() }}
        shell: bash
        run: |
          gcc --version
          cd build
          cmake -DASAN=ON -DCOVERAGE=ON -DSTRICT_ERROR=ON ..
          make
      - name: Run Testcase
        run: ./build/bin/Cbox-test
      - name: Repo covered
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v3
